FROM golang:1.23

RUN apt-get update && apt-get install -y git

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main .

EXPOSE 8070

CMD ["./main"]